# coverage profile for input. default is `coverage.out`.
# input: coverage.out

# coverage profile for input. default is `coverage.out`.
# input-files:
  # - ./path/to/dir1/coverage.out
  # - ./path/to/dir2/coverage.out
  # - ./path/to/dir3/coverage.out

# file for output. default is `coverage.html`.
# output: coverage.html

# HTML color theme to output (`dark` or `light`). default is `dark`
# theme: dark

# output only the specified file or directory.
# include:
  # - internal
  # - ./internal/cover
  # - ./internal/html/tree/html.go

# exclude specified files or directories from output.
# exclude:
  # - internal
  # - ./internal/cover
  # - ./internal/html/tree/
  # - ./internal/html/tree/html.go

# exclude specified function from output.
# exclude-func:
  # - FuncName
  # - (internal/cover).FuncName
  # - (internal/cover.StructName).FuncName
  # - (internal/cover/cover.go).FuncName
  # - (internal/cover/cover.go.StructName).FuncName
  # - (*.StructName).FuncName
